#!/usr/bin/python
"""
 Pefrorm PyQuante calculations to test the functioning of basic OEPDev routines.
 Generate the reference values of various matrices etc, that can be compared with
 those generated by OEPDev plugin (see oepdev::test::Test::test_basic).

 Usage: [anything]
"""
from PyQuante import SCF
from PyQuante.Molecule import Molecule
from numpy import *

def const_init(vec, label):
  log = "const double %s[%d]  = {" % (label, vec.size)
  for i,v in enumerate(vec[:-1]):
      log += "%15.8f," % v
      if not i%5: log += "\n"
  log+= "%15.8f};\n" % vec[-1]
  print log

h2o = Molecule('H2O',
             [(8,       (-3.08471,       1.12313,       0.00396)),
              (1,       (-2.11791,       0.90877,       0.01763)),
              (1,       (-3.12325,       2.07922,      -0.24921))],
                   units='Angstrom')

solver = SCF(h2o,basis='sto3g',method="HF",etol=1e-15)
solver.iterate()
print "Energy: %14.12f" % solver.energy

D = (solver.dmat * 2.0).ravel()
S = solver.S.ravel()
F = solver.F.ravel()
H = solver.h.ravel()

const_init(D, "ref_D")
const_init(S, "ref_S") 
const_init(F, "ref_F")
const_init(H, "ref_H")
