#!/bin/bash
dir_latex_doc=./doc/doxygen/latex
dir_base=$PWD
doxygen Doxygen.config
cp -vr ./misc/latex/* $dir_latex_doc
cp -vr ./misc/latex/algorithmicx/* $dir_latex_doc

cd $dir_latex_doc
make -j`getconf _NPROCESSORS_ONLN`
cd $dir_base

